server:
  port: 9001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/caohonghua/spring-cloud-template-config-repo
          uri: file://${user.home}/spring-cloud-template-config-repo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"